#!/usr/bin/env bash
set -e # halt script on error

JEKYLL_ENV=LOCAL bundle exec jekyll build --verbose
bundle exec htmlproof _site --disable-external --check-favicon --url-ignore "#top", "humans.txt" --checks-to-ignore ScriptCheck --verbose
